### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by mrp13** [tiger9800/3D-Printing#2]
Hi @tiger9800, 
I have successfully cloned the repository to the 3D printing computer and tried to run the main.py from the Anaconda prompt. Below is an image of the line I entered and the error that is created. 
![image](https://user-images.githubusercontent.com/70409604/126530205-7cccaa7d-126f-47f9-a2c8-c3132e6d0552.png)

Following the error's location, in GUI_Code.py it states "import api_calls" but there isn't a file labeled that in the repository. There is a file labeled "API_calls". I wanted to change the import name to correctly match the file name, but didn't know where in GUI_Code that will impact. 
![image](https://user-images.githubusercontent.com/70409604/126530375-02983708-87c4-4ee8-b908-ec45eb782e06.png)

Also, let's fill out the README prompt to include any additional modules that we may need to install in this computer to run this newer version.

**Comment by tiger9800** [comment]
For some reason, git does not care about capitalization, so the fact that I renamed the file on my machine was not reflected here when I committed.
